### PR TITLE
Don't generate the same character twice in a row

### LINKED ISSUE #82: bug: grawlixCensorStrategy sometimes generates "@$$"
### Expected behavior

Censoring strategy should generate a replacement string that itself does not contain any profanity. However, since grawlixCensorStrategy returns a string of random characters that include "@" and "$", sometimes it generates "@$$", which is considered profanity by the default englishDataset/englishRecommendedTransformers matcher recommended in the guide.

### Actual behavior

This causes TextCensor with the default settings to sometimes replace "ass" or "@$$" with "@$$".

### Minimal reproducible example

```typescript
const {
	RegExpMatcher,
	TextCensor,
	englishDataset,
	englishRecommendedTransformers,
} = require('obscenity');

const matcher = new RegExpMatcher({
	...englishDataset.build(),
	...englishRecommendedTransformers,
});

const censor = new TextCensor();
const input = '@$$';
const matches = matcher.getAllMatches(input);
for (let i = 0; i < 100; i++) {
    if (censor.applyTo(input, matches) === input)
        console.log("input did not change after censoring");
}
```

### Steps to reproduce

_No response_

### Additional context

_No response_

### Node.js version

v20

### Obscenity version

v0.4.0

### Priority

- [ ] Low
- [X] Medium
- [ ] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

### PR DESCRIPTION
**Pull request by eltoder**
Fixes #82

**Type of change:**

- [ ] Refactor
- [ ] Performance improvement
- [ ] New feature
- [x] Bug fix
- [ ] Other (please describe):

**Please describe the changes this PR makes and why it should be merged:**

Don't generate the same character twice in a row in randomCharFromSetCensorStrategy(). This produces more interesting strings and avoids generating "@$$" as a side-effect.

**Status:**

- [x] I've added/modified unit tests relevant to my change / not needed
- [ ] This PR contains breaking changes
- [ ] This PR doesn't include changes to the code

### CODE REVIEW

File: src/censor/BuiltinStrategies.ts [hunk 1]
```diff
@@ -139,25 +139,32 @@ export function fixedCharCensorStrategy(char: string): TextCensorStrategy {
...
 	const chars = [...charset];
-	if (chars.length === 0) throw new Error('The character set passed must not be empty.');
+	if (chars.length < 2) throw new Error('The character set passed must have at least 2 characters.');
 	return (ctx: CensorContext) => {
 		let censored = '';
-		for (let i = 0; i < ctx.matchLength; i++) censored += chars[Math.floor(Math.random() * chars.length)];
+		let prev = chars.length;
+		for (let i = 0; i < ctx.matchLength; i++) {
+			let idx = Math.floor(Math.random() * (i ? chars.length - 1 : chars.length));
+			if (idx >= prev) idx++;
```
Comment (jo3-l) [inline src/censor/BuiltinStrategies.ts:164]: It took me a second to realize the code is written the way it is to ensure a uniform distribution of generated characters at each iteration. I think it would be worth adding a brief comment to that effect, and wonder if separating the first iteration from the rest would help clarity:
```js
if (ctx.matchLength === 0) return ''; // at the start of the function

const firstIdx = Math.floor(Math.random() * chars.length);
let censored = chars[firstIdx];
let prev = firstIdx;
for (let i = 1; i < ctx.matchLength; i++) {
	let idx = Math.floor(Math.random() * (chars.length - 1));
	if (idx >= prev) idx++;
	prev = idx;
	censored += chars[idx];
}
return censored;
```
(To be precise on what I'm requesting, I would like you to add the comment, but separating out the first iteration is optional; I'm happy to leave it as is if you think it doesn't help structurally.)

**Review by jo3-l — CHANGES_REQUESTED** [review]
Thanks, this is nice! One minor nit, if you don't mind:

**Comment by eltoder** [comment]
@jo3-l Updated. Please take another look.

**Review by jo3-l — APPROVED** [review]
LGTM, thank you!
